INSERT INTO produto (nome, descricao, preco, estoque, imagem_url) VALUES
('Java Efetivo', 'Melhores práticas para programadores Java', 150.00, 20, '/img/produtos/java-efetivo.jpg'),
('Spring Boot em Ação', 'Aprenda a criar aplicações modernas com Spring Boot', 90.50, 12, '/img/produtos/spring-boot-em-acao.jpg'),
('PostgreSQL Essencial', 'Guia básico de banco de dados PostgreSQL', 70.00, 25, '/img/produtos/postgresql-essencial.jpg'),
('Algoritmos e Estruturas de Dados', 'Fundamentos de ciência da computação', 110.00, 18, '/img/produtos/algoritmos-estruturas-dados.jpg'),
('Arquitetura Limpa', 'Estrutura e design de software robusto', 130.00, 10, '/img/produtos/arquitetura-limpa.jpg'),
('Padrões de Projeto', 'Design Patterns em Java explicados', 140.00, 22, '/img/produtos/padroes-de-projeto.jpg'),
('Refatoração', 'Melhore o design do seu código existente', 125.00, 16, '/img/produtos/refatoracao.jpg'),
('Domain-Driven Design', 'Abordagem estratégica para modelagem de software', 160.00, 8, '/img/produtos/domain-driven-design.jpg'),
('Testes Unitários em Java', 'Boas práticas de testes automatizados', 95.00, 30, '/img/produtos/testes-unitarios-java.jpg'),
('Microsserviços na Prática', 'Criação de microsserviços escaláveis', 135.00, 14, '/img/produtos/microsservicos-na-pratica.jpg'),
('Cloud Computing', 'Conceitos e fundamentos da nuvem', 150.00, 12, '/img/produtos/cloud-computing.jpg'),
('Machine Learning', 'Introdução ao aprendizado de máquina', 170.00, 20, '/img/produtos/machine-learning.jpg'),
('Inteligência Artificial', 'Fundamentos e aplicações práticas', 180.00, 15, '/img/produtos/inteligencia-artificial.jpg'),
('Redes de Computadores', 'Conceitos essenciais de redes', 115.00, 28, '/img/produtos/redes-computadores.jpg'),
('Engenharia de Software Moderna', 'Métodos ágeis e boas práticas', 145.00, 19, '/img/produtos/engenharia-software-moderna.jpg'),
('Sistemas Operacionais', 'Conceitos e fundamentos', 105.00, 23, '/img/produtos/sistemas-operacionais.jpg'),
('Estruturas de Dados Avançadas', 'Algoritmos eficientes para problemas complexos', 155.00, 17, '/img/produtos/estruturas-dados-avancadas.jpg'),
('Programação Concorrente em Java', 'Threads e paralelismo', 140.00, 14, '/img/produtos/programacao-concorrente-java.jpg'),
('Kotlin para Java Developers', 'Transição de Java para Kotlin', 130.00, 20, '/img/produtos/kotlin-para-java-developers.jpg'),
('Programação Funcional', 'Paradigma funcional aplicado em várias linguagens', 125.00, 18, '/img/produtos/programacao-funcional.jpg'),
('Desenvolvimento Web com Spring MVC', 'Framework Spring MVC na prática', 115.00, 21, '/img/produtos/desenvolvimento-web-spring-mvc.jpg'),
('Segurança em Aplicações Web', 'Boas práticas de segurança no desenvolvimento', 135.00, 19, '/img/produtos/seguranca-aplicacoes-web.jpg'),
('REST APIs com Spring Boot', 'Criação de APIs RESTful eficientes', 120.00, 16, '/img/produtos/rest-apis-spring-boot.jpg'),
('Hibernate e JPA', 'Mapeamento objeto-relacional em Java', 140.00, 15, '/img/produtos/hibernate-jpa.jpg'),
('NoSQL Databases', 'MongoDB, Cassandra e Redis', 150.00, 11, '/img/produtos/nosql-databases.jpg'),
('Big Data Fundamentals', 'Processamento de grandes volumes de dados', 175.00, 13, '/img/produtos/big-data-fundamentals.jpg'),
('Docker para Desenvolvedores', 'Containerização simplificada', 125.00, 22, '/img/produtos/docker-para-desenvolvedores.jpg'),
('Kubernetes em Ação', 'Orquestração de containers em escala', 165.00, 10, '/img/produtos/kubernetes-em-acao.jpg'),
('DevOps Culture', 'Integração de desenvolvimento e operações', 145.00, 18, '/img/produtos/devops-culture.jpg'),
('Git e GitHub', 'Controle de versão distribuído na prática', 90.00, 40, '/img/produtos/git-github.jpg'),
('CI/CD Pipelines', 'Integração e entrega contínua', 135.00, 15, '/img/produtos/cicd-pipelines.jpg'),
('Frontend com React', 'Biblioteca JavaScript moderna', 110.00, 25, '/img/produtos/frontend-react.jpg'),
('Angular Essencial', 'Framework frontend completo', 120.00, 18, '/img/produtos/angular-essencial.jpg'),
('Vue.js Rápido e Prático', 'Desenvolvimento frontend ágil', 115.00, 20, '/img/produtos/vuejs-rapido-pratico.jpg'),
('HTML e CSS Moderno', 'Fundamentos de front-end', 85.00, 30, '/img/produtos/html-css-moderno.jpg'),
('JavaScript Avançado', 'Conceitos modernos de ES6+', 105.00, 26, '/img/produtos/javascript-avancado.jpg'),
('TypeScript Definitivo', 'JavaScript tipado para grandes projetos', 115.00, 24, '/img/produtos/typescript-definitivo.jpg'),
('Node.js em Produção', 'Backend moderno com JavaScript', 125.00, 22, '/img/produtos/nodejs-em-producao.jpg'),
('Express.js na Prática', 'APIs e aplicações backend', 120.00, 21, '/img/produtos/expressjs-na-pratica.jpg'),
('Python para Iniciantes', 'Fundamentos de programação em Python', 90.00, 35, '/img/produtos/python-para-iniciantes.jpg'),
('Data Science com Python', 'Análise de dados prática', 135.00, 18, '/img/produtos/data-science-python.jpg'),
('Django Web Framework', 'Desenvolvimento web com Python', 125.00, 16, '/img/produtos/django-web-framework.jpg'),
('Go para Desenvolvedores', 'Linguagem Go na prática', 140.00, 15, '/img/produtos/go-para-desenvolvedores.jpg'),
('Rust em Ação', 'Programação segura e performática', 160.00, 12, '/img/produtos/rust-em-acao.jpg'),
('C++ Moderno', 'Recursos do C++11 e posteriores', 155.00, 14, '/img/produtos/cpp-moderno.jpg'),
('C# Essencial', 'Linguagem moderna da Microsoft', 125.00, 20, '/img/produtos/csharp-essencial.jpg'),
('ASP.NET Core', 'Framework web da Microsoft', 135.00, 18, '/img/produtos/aspnet-core.jpg'),
('SQL Completo', 'Consultas e modelagem de dados', 115.00, 25, '/img/produtos/sql-completo.jpg'),
('MySQL para Desenvolvedores', 'Banco relacional popular', 110.00, 22, '/img/produtos/mysql-para-desenvolvedores.jpg');
